electronics/pcb_util.py
Resolves "TODO: add the rest" by supporting all the layers available in the layout and removes the need for a custom layer name table.
Not that getting the layer name of a non-existing layer id will now result in the "BAD INDEX!" layer name iof. "Unknown(<layer_id>)". It might be a good idea to check for this or even to fail / raise an exception when attempting to plot a non-existing layer.
I found out about this function while working on https://github.com/productize/kicad-automation-scripts, a collection of useful KiCad scripts I started as a part of https://github.com/productize/kicad-file-render-service. Both these projects where based heavily on your work, thanks a lot for sharing it.
=> Use PCB.GetLayerName to get layer name

arduino/splitflap/.gitignore, arduino/splitflap/.travis.yml, arduino/splitflap/.vscode/extensions.json, arduino/splitflap/Splitflap/Splitflap.ino, arduino/splitflap/Splitflap/acceleration.h, arduino/splitflap/Splitflap/basic_io_config.h, arduino/splitflap/Splitflap/generate_acceleration.py, arduino/splitflap/Splitflap/spi_io_config.h, arduino/splitflap/Splitflap/splitflap_module.h, arduino/splitflap/include/README, arduino/splitflap/lib/README, arduino/splitflap/platformio.ini, arduino/splitflap/test/README
PlatformIO offers library management and a lot more powerful development tools. This migrates the project to support PlatformIO without breaking Arduino IDE compatibility for those that are more familiar with Arduino.
=> Migrate to platformio with Arduino IDE compatibility

.travis.yml, 3d/generate_2d.py, 3d/openscad.py
Skip rendering raster images by default (only really used for Travis build to generate images for the README).
Added a better error message if you don't have openscad installed.
=> Improve generate_2d.py

3d/splitflap.scad
Rounds the corners of the motor window (r=5) for slightly more stiffness and a nicer fit + finish. With a radius of 5 mm this should still be a loose fit around the motor (at least according to the model). On the flat panel the spool retaining wall was moved to the X center of the window to clear the rounded corners while still maintaining its shared bottom edge.
This also adjusts the lasercut panel so that the module connector pieces won't cut material out of the enclosure's left side. To do this the top and bottom pieces were moved down and the connectors were nested between the tabs in the top right corner. This keeps within the existing boundaries of the panel so it uses no extra material.
For what it's worth these new connector positions break down and start intersecting the other …
=> Round motor window and CAD tweaks

3d/scripts/projection_renderer.py, 3d/scripts/svg_processor.py
Currently the combined SVG output from `generate_2d.py` uses the dimensions and [viewbox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) from the first merged file. This causes the combined SVG to render incorrectly in browsers and most viewing software, as the content extends outside of the viewing bounds. To fix it, this PR adds a few functions to the Python scripts which recalculate and set the new dimension and viewboxes for the combined SVG based off of the imported files.
Before:
After:
(screen captures from Inkscape 1.0.1, 3bc2e813f5, 2020-09-07 - Using `View->Zoom->Drawing`)
As files are added to the combined SVG (`import_paths()`), the imported viewbox is compared against the current one. If the imported viewbox is larger in any dimension, the current viewbox …
=> Recalculate SVG viewbox after combining

3d/pcb.scad
Small PR, just rounding the enclosure's PCB cutouts so they're a little nicer.
=> Round corners of sensor PCB cutouts

3d/splitflap.scad, 3d/spool.scad
As I was starting to put the flaps in my enclosure I thought it would be really nice if there was some sort of indicator for which hole was for the 'home' flap. So I added one:
=> Etched home flap indicator

3d/rough7380.scad, 3d/scripts/colored_stl_exporter.py, 3d/splitflap.scad
I've made a number of changes to the assembly to make it easy to adjust the colors.
First, the assembly color variations are now generated from a single base color. This means you can change the one 'assembly' color and still keep the color variation between parts. The scalars were calculated from the current values so everything should keep the same appearance as before. The etch color, similarly, has been broken out into a variable and can now be changed.
Second, I've added variables for the hardware (nuts + bolts) and flap color. This allows you to change out the steel hardware for black oxide or swap the flaps from white to black. The letter color is calculated as the inverse of the flap color, so white flaps get black letters and black flaps get white letters (and red flaps get cyan …
=> CAD Render Colors

3d/pcb.scad, 3d/splitflap.scad
This PR dynamically adjusts the hall effect sensor's height off of the PCB in the model based on its distance from the spool. The sensor will maintain the same relative distance from the spool as the model is changed and throw an error if its distance from the PCB exceeds the max length of the sensor's leads (per the datasheet). I also created a small lasercut jig that fits between the PCB and the sensor to aid in soldering.
Using your v0.5 sensor assembly video as reference, I set the spool offset to `0.7 mm` which corresponds to a distance of `5.8 mm` from the PCB. Note that this PR has a conflict with #100 that will need to be resolved, as the new jig is cut out of the motor window area.
Here are some demonstration gifs, using a change in material thickness (3.2 -> 1.0) to show the …
=> Hall Effect Sensor Spacing and Jig

3d/pcb.scad, 3d/pcb_case.scad
As with the flap case (#103), while I'm waiting for the enclosures to be finished I have a bunch of assembled sensor PCBs sitting around. This is a little dangerous since the hall effect sensors stick out from the board and can be accidentally bent out of position. So I designed a 3D printed case for them to safely sit in until the modules can be assembled.
The design has a `cases_per_row` parameter for generating multiple cases in one design, as well as a `dual_rows` parameter that mirrors a second row along the back for double the number of PCB spots:
=> Sensor PCB Case

3d/splitflap.scad
This PR makes a few minor adjustments to how the spool assembly fits together.
First and most importantly, the `spool_tab_clearance` value, which affects the fitment between the spool struts and the spool end pieces, has been changed from a slight clearance / free fit (`0.1 mm`) to a slight interference fit (`-0.02 mm`). This was an oversight - the spool, as designed, needs to be an interference fit otherwise the spool endpieces fall right off. Mea culpa.
The spool struts themselves, as well as the spool retaining wall, will keep their `0.1 mm` clearance value so they'll fit together smoothly. This also gives you a little bit of wiggle room when trying to slot the spool struts into the interference-fit endcaps, which will undoubtedly be a little tricky with an acrylic enclosure.
This also …
=> Spool Fitment Adjustments

3d/tools/flap_container.scad, 3d/tools/pcb_case.scad, 3d/tools/punch_jig.scad, 3d/tools/scoring_jig.scad, README.md
Collects all of the 3D printed tool designs in a subfolder to try and keep the CAD files at least somewhat organized. Also fixes a bug with the optional PCB rendering in the PCB case design and adds a section to the README about these designs (per your comment in #103 :smile:).
=> Organize 3D printed tools

arduino/splitflap/Splitflap/Splitflap.ino, arduino/splitflap/Splitflap/src/spi_io_config.h, software/splitflap.py
A few small quality of life changes to the software:
* Prints the flap character array over serial (JSON) during initialization.
* Adds an `__unused__` attribute to the `new` operator override used for static placement of the module objects, which was creating a warning during compilation.
* Reads the reported flap character array if present during initialization, and uses that instead of `_ALPHABET` to filter characters. This allows the Python script to talk to displays with any character set without having to modify the script's array. Includes a `KeyError` catch to support previous firmware that does not report its character set.
* Truncates the text being sent (`set_text()`) to the size of the display (number of modules). This prevents verification issues when the number of modules in …
=> Character Reporting + Software Tweaks

3d/shapes.scad, 3d/splitflap.scad, 3d/spool.scad
Adds alignment indicators to the enclosure to aid in assembly: a triangle on the left side, a circle on the right side, and an 'up' arrow on the front face. The goal is to provide an easy visual cue for how the enclosure pieces fit together - particularly the front piece, which is slightly asymmetric. I opted not to add indicators to the top and bottom pieces because they seemed a little redundant.
The triangle and arrow geometry were added through modules included in a new `shapes.scad` file. This also includes the rounded rectangle module that was submitted separately as a part of PR #109 (Zip Ties).
I also cleaned up the other etched features in the design and removed the 3D difference feature for the etched spool indicators which struck me as excessive. All etched features now go …
=> Alignment Indicators

3d/splitflap.scad
Adds holes for cable management zip ties into the left side of the enclosure: one pair underneath the sensor PCB for wires exiting downwards (PCB behind module) and one pair above the motor for wires exiting upwards (PCB mounted on top of module(s)). The goal is to prevent the wires from bending outwards and getting tangled in the moving spools of adjacent modules.
These are sized to work with your typical 2.5 mm wide mini zip ties.
=> Zip Ties for Cable Management

3d/scripts/generate_2d.py, 3d/scripts/projection_renderer.py, 3d/splitflap.scad
This adds the option to mirror the 2D laser-cut design so that the outside faces are facing 'up' / towards the laser when cut. This is useful for materials with a special finish on only one side like Ponoko's matte black acrylic, which is cut with the matte finish facing towards the laser.
The mirroring can be set with the `render_2d_mirror` flag, or with the `--mirror` option in the `generate_2d.py` script.
This continues the conversation from PR #100, and offers an alternate solution to the same issue.
=> Laser Layout Mirror Option

3d/splitflap.scad
This increase was a mistake. The difference in thickness (0.2 on either side) should have been added to the *spool* slop instead of the flap width slop, as the inner width of the spool (flap_width_slop) was not affected by the thickness parameter, while the outer width of the spool (spool_width_slop) *was*. This commit corrects that oversight.
This reverts commit a68fc988bc73c146c28ed1dc2c8e02c990d5ab93 (squashed as part of 7be69dbeb4fb7c1aa4b29027eb3e49a9b121c6a2).
=> CAD: Move flap thickness slop to spool slop

arduino/splitflap/Splitflap/Splitflap.ino
**Intended goal:** enable repeat occurrences of the same character within `flaps[]`, for specific applications of splitflap displays (e.g. countdown clocks with more than 10 flaps).
In the use-case of a countdown clock (e.g. train arrival time countdown) the `flaps[]` definition might look something like this:
```
#define NUM_FLAPS (40) // Using 40 despite only 10 characters needed, to avoid significant hardware customization
const uint8_t flaps[NUM_FLAPS] = {
'9', '8', '7', '6', '5', '4', '3', '2', '1', '0',
'9', '8', '7', '6', '5', '4', '3', '2', '1', '0',
'9', '8', '7', '6', '5', '4', '3', '2', '1', '0',
'9', '8', '7', '6', '5', '4', '3', '2', '1', '0'
};
```
Currently, when moving from the character '0' to the character '9', the module would turn from index 9 all the way around to …
=> Go to next occurence of a repeated character

3d/splitflap.scad
On my latest order from Ponoko (3 mm acrylic) the spool struts are still loose and will need to be glued. This increases the interference a bit more (+ 0.04 mm) to hopefully reach a point where the struts will fit into the spool and hold there by friction alone.
Also increased is the flap width slop, in a reversion to the change from #114. On my order based around f4e7714 the flaps do *fit* and swing but it's tight - a little bit of misalignment with the spool end pieces or burrs on the parts will cause them to bind. And after gluing the end pieces in place not *perfectly* parallel (+/- 0.15 mm across ~48 mm diameter) that's exactly what has happened: some flaps on the spool do not 'flip' freely which breaks the whole display.
Originally I thought a slight increase to the flap slop would …
=> CAD: Tweak Spool Fitment Values

3d/tools/flap_container.scad
I think the default should add a bit more tolerance to the hight of the cavity.  I just printed it and it's about 3 cards too low for me.  Perhaps the vinyl added unexpected thickness.  I think 3mm extra should be good.
=> Add more tolerance to cavity_top_allowance

3d/splitflap.scad
Increases the clearance between the motor chassis and the right outside wall of the previous module. Also refactors this variable from 'slop' to 'clearance' for a better description of what it represents.
This is still playing a bit of catch-up from the thickness change (#93). In the previous release where the thickness parameter was set to 3.2 mm but the manufactured panels were actually 3.0 mm thick, there was extra space between the motor chassis and the previous module. This change adds that additional 0.4 mm of clearance back as part of the motor clearance variable.
The additional clearance also makes the widths between the two designs approximately equal - `enclosure_width` is 82.2 mm on v0.6, and 82.25 mm here. (The discrepancy is the additional 0.05 of flap width slop that was …
=> CAD: Increase Motor Clearance

3d/splitflap.scad, 3d/tools/connector_case.scad
Since the connector pieces are a little fragile on there own and are not necessarily used for each module I designed a 3D printable case to store them. The design is modular and can be extended based on:
* The number of connectors per stack
* The number of stacks per row
* The number of rows per design (1 or 2)
Each stack of connectors can be retained with a rubber band. I've printed my own 3x2 version and it works great.
=> Module Connector Case

3d/splitflap.scad
On my latest build the edges of the enclosure's front panel are not cut perfectly perpendicular, which effectively increases the front panel width. When using connectors this excess width pushes the modules further apart, causing the display to bow backwards.
This increases the connector clearance so the module connections have a little bit of play, in order to compensate for tolerance issues on the front panel.
=> CAD: Increase connector clearance

electronics/sensor.kicad_pcb
Fixes the sensor PCB `Edge.Cuts` layer continuity and moves the commit silkscreen off of the pads.
These commits were cherry-picked from PR #97
=> Sensor PCB Tweaks

arduino/splitflap/Splitflap/src/spi_io_config.h
These pin mode lines were removed as part of the chainlink driver PR (#132) and the consolidation to `LATCH_PIN` for the ESP32, which broke compilation for the "classic" driver on the Arduino Uno. Replacing these lines fixes the compilation error.
=> Fix firmware compilation for Uno

software/demo.py, software/flap_test.py, software/splitflap.py, software/terminal.py
Adds two new Python software scripts:
* **flap_test.py**, which homes the display and then runs through all flaps one at a time (1s between).
* **terminal.py**, which passes strings from input prompts to the display, checking for lower/uppercase alternatives and padding with spaces.
This also moves the `print_status` and `ask_for_serial_port` functions to the `splitflap` module to share them between scripts, and adds a `get_num_modules` function.
=> Additional Python Software Scripts

3d/shapes.scad, 3d/splitflap.scad
Creates a hole in the left enclosure panel that is aligned with the back edge of the right side of the enclosure, to be used with a dowel rod or other round stock as an alignment aid for multiple modules.
The connector pieces are a bit of a pain to use since you have to remove the front panels and deal with the captive nuts that can be hidden underneath a full spool of flaps. This creates an alternate way to align the back edge of the modules without extending the length of the right panel and increasing the size and cost of the laser-cut design. In larger displays it also allows modules to be swapped out without having to undo any of the hardware.
Note that this does *not* prevent the module from twisting forwards about the alignment hole (along Z), and it would need either an …
=> Enclosure Alignment Bar

3d/tools/punch_jig.scad
In order to cater for flaps that aren't cut precisely on the corners and for printers that create a small radius, cut out the corner of the punch jig to allow flaps to sit tightly into the corner.
=> Add corner relief to punch jig

util/rev_info.py
Will return "notfound" as the commit hash in cases where git is unavailable or the invoked script is not part of a git repository. This allows export scripts to work if the user downloads the repo without git cloning it.
=> rev_info.py: print helpful message if git command fails

3d/font_generator.scad, 3d/scripts/generate_fonts.py, 3d/splitflap.scad
This allows the generation of double-sided flaps, ideal for laser cutters/printers.
This PR adds the following arguments to `generate_fonts.py`:
* `--double-sided`: Generate a double-sided version of the flaps, for double-sided printing and laser-cutting.
* `--bleed`: Bleed the letters. This allows some margin for error during double-sided printing and laser-cutting.
* `--start-row`: The row to start rendering. Combined with the `--row-count`, this allows pagination of the flaps.
* `--row-count`: How many rows to render.
Demo:
https://user-images.githubusercontent.com/7296537/116824424-20c22c00-ab58-11eb-9018-0786b54eec7b.mov
Sample of Generated Flaps:
=> Allow generation for double-sided flaps

.github/workflows/pio.yml
Followed the instructions at https://docs.platformio.org/en/latest/integration/ci/github-actions.html to add the GitHub Action.
Since I was unsure which platformio environments are active, I included all of them.
Should close #141.
=> Integrate PlatformIO to CI Workflow

.github/workflows/3d.yml, 3d/scripts/dependencies.sh, 3d/scripts/generate_2d.py, 3d/scripts/svg_processor.py
- Add 4x panelized output generation
- Generate text files that describe the dimensions of each SVG file (for verifying SVG processors - e.g. Ponoko - are handling dimensions correctly)
- Add Elecrow wood kerf preset and zipped PDF generation: no etching, black lines, labeled dimensions
Example output pdf: [elecrow.pdf](https://github.com/scottbez1/splitflap/files/6751491/elecrow.pdf)
=> Improve 3d laser artifact generation

3d/28byj-48.scad, 3d/pcb.scad, 3d/splitflap.scad, 3d/tools/motor_test_jig.scad
3d printable piece to hold a motor+sensor and a maget arm for the motor, for testing motors and sensors (e.g. gear ratio, or basic movement tests).
=> Add jig for testing motor+sensor

3d/shapes.scad, 3d/splitflap.scad, 3d/tools/mounting_bracket.scad
Creates `mounting_bracket.scad` which generates geometry for 3D-printable mounting brackets. Two brackets are defined, using the same common base geometry:
* `mounting_bracket_t_slot` for mounting a module to an M4-sized T-slot, using an M4-12 bolt and matching T-nut.
* `mounting_bracket_screw_holes` for mounting a module to a wooden board using flat-head M4 screws. The hole for the enclosure's bolt either needs to be undersized for thread engagement or enlarged for a heat-set insert (user's choice).
The base geometry uses the existing hole in the bottom enclosure piece and juts up against the left and right enclosure sides to prevent the module from twisting.
This also adds three more functions to `shapes.scad`: one to create a 3D rounded fillet on a corner, one to create a 3D rounded …
=> Mounting Brackets

3d/splitflap.scad, 3d/tools/mounting_bracket.scad
Exports are now in one place, ordered alphabetically, and have a standardized `get_` prefix
=> 3d: Group together and standardize naming for variable exports

3d/splitflap.scad
Previously the front face and tabs were all centered between the left and right walls, but this resulted in features looking oddly off-center when viewed from the front (where the walls aren't visible and the only other visible feature is the window).
This changes the tabs and front face positioning so that everything is centered relative to the front window. The tabs are made slightly smaller, and the top/bottom pieces are no longer horizontally symmetric as a result. This is not a breaking change (overall dimensions are all the same), but this could not be placed to the _right_ of older modules since the front face has shifted and the motor sticks out further relative to the edge of that face.
=> Center front face, tabs, and bolts relative to the window

.github/workflows/electronics.yml, README.md, docs/index.html
The Electronics action was starting to get a bit slow, mostly because of the 3d PCB rendering of 3 different PCBs (chainlinkDriver, chainlinkBase, and chainlinkDriverTester), so this splits that action into 3 separate jobs that can run in parallel. This requires separating the artifacts from each of the different electronics jobs, so all references had to be updated too.
Now the build duration is dominated by the environment setup and code checkout, which can be addressed separately.
=> Split Electronics GitHub Actions into separate jobs

3d/flap.scad
At the current state, when you use the `generate_font.py` file, the generated svgs are quite low poly. This is due to the facet number on `facet.scad` is set 0 as default. 
If we look at the image below, the first one is what you would get if you generated the fonts. I was asked by the man himself, Scott, to try 60, but it's not quite smooth enough. So I just doubled the value and tried 120. 120 gave me cleaner and more refined results. 
But the [docs ](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Other_Language_Features#.24fa.2C_.24fs_and_.24fn) don't recommend going beyond 100, so this pull request is using 100 but feel free to modify to your needs.
=> Add $fn parameter to have smoother edges when generating svg fonts

software/demo.py, software/splitflap.py, software/terminal.py
Three small quality of life changes to the software script:
* Initializes `character_list` with the default character set, for attempting to filter characters (`in_character_list()`) even if the display is not initalized.
* Adds a `get_text()` helper function, for retrieving the currently displayed string from the status message.
* Adds a serial timeout (1 second), so if the device is not responding the script can be interrupted gracefully without having to kill the process.
=> Software QOL Changes

3d/combined_front_panel.scad, 3d/scripts/generate_combined_front_panel.py, 3d/splitflap.scad
- Add `--center-window` option to vertically center the modules based on their window, rather than the default of centering based on flap/letter centers
- Improve export performance drastically by omitting the 3d splitflap modules entire in projection rendering mode
- Fix `--center-center-x` and `--center-center-y` arguments
- Change dog bone shape (and front face M4 hole) to rectangles to simplify the 2d geometry that's exported for external CAM (Fusion 360 did not perform well with all of the polygon-ized cricles)
=> Front panel generation improvements

3d/combined_front_panel.scad, 3d/scripts/generate_combined_front_panel.py, 3d/splitflap.scad
- Add frame margin mode (to size frame based on module size)
- Add module vertical centering mode
- Minor improvements to make it easier to export front panels directly from OpenSCAD
```
./3d/scripts/generate_combined_front_panel.py --rows 1 --cols 4 --frame-margin-x 0 --frame-margin-y 0 --spacing-x 0 --spacing-y 0 --center-mode module --kerf-preset ponoko-3mm-mdf
```
```
./3d/scripts/generate_combined_front_panel.py --rows 6 --cols 18 --width 2438.4 --height 1219.2 --center-center-x 101.6 --center-center-y 184.15 --center-mode window --tool-diameter 3.5
```
=> Front panel improvements

3d/scripts/kerf_presets.py, 3d/sensor_pcb_dimensions.scad, 3d/splitflap.scad
- increase clearance for PCB connector pins (slot width)
- remove spool tab interference (kerf value isn't accurate enough anyway, and undersizing requires labor-intensive filing/sanding whereas oversizing just requires a little glue)
- shrink spool axle M4 hole to get less spool "sag" due to unnecessary clearance
- decrease interference on magnet hole (again, an undersized hole is labor intensive to fix whereas oversized just requires a dot of glue in the worst case)
- add Elecrow acrylic kerf value that has been tested
=> Tweak fit parameters; add Elecrow acrylic kerf value

3d/scripts/generate_2d.py, 3d/scripts/generate_fonts.py, 3d/scripts/openscad.py, 3d/scripts/svg_processor.py, util/app_paths.py, util/inkscape.py
- Added application executable lookup for Windows and Mac OS where openscad and inkscape don't get added to PATH.
- Added Inkscape argument helpers for CLI arguments that changed in version 1.0
- Added helpful message if `svg.path` python library is missing
=> Add basic Windows and Mac OS support to 3d scripts, support Inkscape 1.0

3d/scripts/generate_2d.py, 3d/scripts/svg_processor.py
PDFs generated for elecrow on the latest master currently look like this:
Dimensions appear to be placed incorrectly when the svg output is mirrored. I updated `add_dimensions` to account for mirroring when its enabled.
I tested this in a 20.04 docker container setup similarly to the actions environment and the output looks correct. Result is below:
[elecrow_dim_fix.pdf](https://github.com/user-attachments/files/15907775/elecrow_dim_fix.pdf)
When testing locally, I also discovered that the inkscape cli has deprecated `--verbs`  in favor of `--actions` in version 1.2+. This PR adds a check to handle both inkscape < 1.2 and >= 1.2 when generating elecrow pdfs
=> Elecrow v2 export fixes

arduino/splitflap/Splitflap/config.h, software/chainlink/demo.py, software/chainlink/splitflap_proto.py
- Replaced `~` with `@` in default v2 character set to match shipped flaps
- Get character set from splitflap display (if possible, otherwise use previous legacy alphabet)
- Use upper case in demo words to match new character sets
=> Update Python example (and v2 character set) for new features

3d/scripts/requirements.txt, 3d/scripts/svg_processor.py
Fixes #115
The fix from #116 was previously applied but wasn't quite working on svg.path 6.3, and it looks like the issue was that svg.path doesn't enforce/check consistency between adjacent path elements now that Moves are tracked separately from Lines, so after modifying lines and omitting Moves, the `d` string generated for the Path didn't have correct Moves to handle the gaps between adjacent Line start/ends.
This change continues treating Close as a Line (and continues omitting Moves from the original path), and now inserts Move elements in the reconstructed Paths when there's a mismatch between adjacent Line end/start points.
=> Fix line optimizations for newer svg.path

3d/tools/flap_container.scad
Otherwise we get warnings, and things won't render!
```
WARNING: Ignoring unknown module 'flap_2d' in file flap_container.scad, line 76
WARNING: Ignoring unknown module 'flap_2d' in file flap_container.scad, line 118
```
=> flap_container.scad: use flap.scad

3d/splitflap.scad
The connector slot on the enclosure side pieces has historically left a thin sliver of material on the corners of the side pieces that was prone to breaking during shipping, especially for acrylic.
This change should make the entire connector system less fragile by:
- moving the connectors from outside the enclosure top/bottom pieces to inside, which removes the thin sliver previously left by the slot cutout - circled in red below
- (there is some risk from this change that flaps will catch on it, so I'll need to validate this change in practice. I added a fillet to the outer corners to make it less likely that this will scratch flaps if they do end up in contact)
- ~adds fillets to the connector slots on the enclosure pieces and the connector itself, circled in green below~
- increases …
=> Make connector less fragile, move inside top/bottom enclosure

.github/workflows/js.yml
Since 2025-01-30 the JS workflow has been failing with:
This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
This commit bumps two action versions to repair the workflow.
=> fix(ci): bump action versions to fix JS workflow

firmware/esp32/splitflap/http_task.cpp, firmware/esp32/splitflap/mqtt_task.cpp, firmware/src/spi_io_config.h, platformio.ini
* Disable WiFi power saving to avoid sensor data glitches
* Also update platformio espressif platform which was very outdated (note: this may result in a flash rewrite that wipes saved module calibration data!)
* Enabling Wifi previously would cause intermittent "unexpected home" events on arbitrary modules (and sometimes on one of the loopback inputs, causing all modules to be disabled)
* This issue appears related to ESP32 errata 3.11 "When certain RTC peripherals are powered on, the inputs of GPIO36 and GPIO39 will be pulled down for approximately 80ns."
* Credit to this thread - https://github.com/espressif/arduino-esp32/issues/4903#issuecomment-793442683 - for describing a similar issue and providing a workaround
* Correlation with glitches on pin 39 (used as MISO for SPI-based …
=> Avoid SPI input glitches from wifi
